---
language: php
php:
- 5.3
- 5.4
- 5.5
- 5.6
before_script:
- sudo apt-get update > /dev/null
- sudo apt-get install -qq graphviz libmagickwand-dev
- build/getTools.sh
- phpenv rehash
- composer self-update
- composer install
- composer update

matrix:
  allow_failures:
  - php: 5.6
script:
- ant travis -Dphpunit.testdox=true -Dpackage.version=$TRAVIS_BUILD_NUMBER
